---
- name: Deploy PeerHire API using Docker Compose
  hosts: ec2
  become: yes

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose (v2 style using plugin)
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create app directory
      file:
        path: /home/ec2-user
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user

